services:
  # Backend API
  - type: web
    name: trading-metrics-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        fromService:
          type: web
          name: trading-metrics-backend
          property: port
    
  # Frontend (Static Site)
  - type: web
    name: trading-metrics-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build && cp public/_redirects dist/ && cp public/render.json dist/ && cp public/404.html dist/
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://trading-metrics-backend.onrender.com/api